name: Ejecutar pruebas de Selenium y generar reporte HTML

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pruebas-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas de Selenium y generar reporte HTML
        run: |
          pytest tests/AutomationTP.py --html=reporte.html --self-contained-html

      - name: Subir el reporte HTML
        uses: actions/upload-artifact@v3
        with:
          name: reporte-selenium
          path: reporte.html
